### ISSUE TITLE
Skrypt prepare_data_ttt_z3.py nie konwertuje do integer encoding

### ISSUE THREAD

**Issue by ath0m** [lorek/ZPS2020#17]
Zbiór danych `tic_tac_toe` nie jest przekonwertowany do *integer encoding*.

Zawartość pliku `datasets_prepared/ttt_z3_prepared/train_data.pkl`:
![image](https://user-images.githubusercontent.com/7113266/97929010-7fa11700-1d68-11eb-9710-6a27d18fc5e3.png)

**Comment by lorek** [comment]
Rozumiem, że rozwiązane. Zamykam.
